import React, { useEffect, useState } from "react";
import styles from "../../Sass/addCategoryModal.module.scss";
import { ColorPicker, useColor } from "react-color-palette";
import { writeCategory } from "../../firebaseFunctions/Categories.ts";
import { useAuth } from "../../context/authContext.js";
import EmojiPicker from "emoji-picker-react";
import { Emoji, EmojiStyle } from "emoji-picker-react";
import { toggleCategoryModal } from "../../store/toggleModals/toggleModalSlice";
import { useSelector, useDispatch } from "react-redux";
import { selectCategoryModal } from "../../store/toggleModals/toggleModalSlice";
import { AppDispatch } from "@/app/store/store.ts";
import {
  standardErrorToast,
  categoryAddedToast,
  noEmojiSelectedToast,
} from "../../toastNotifications.tsx";
export default function AddCategoryModal() {
  const [categoryToAdd, setcategoryToAdd] = useState("");
  const [color, setColor] = useColor("rgb(0,0,0)");
  const { user } = useAuth();
  const [emojiPicker, setEmojiPicker] = useState(true);
  const [selectedEmoji, setselectedEmoji] = useState<string>("");
  const dispatch: AppDispatch = useDispatch();
  const isCategoryModalOpen = useSelector(selectCategoryModal);
  const [isFlashing, setIsFlashing] = useState(false);

  // Set up the flashing effect
  useEffect(() => {
    if (emojiPicker !== null) {
      const flashInterval = setInterval(() => {
        setIsFlashing((prev) => !prev);
      }, 500); // Toggle flashing state every 800ms

      return () => clearInterval(flashInterval);
    }
  }, [emojiPicker]);

  const addCategory = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (selectedEmoji === "") {
      noEmojiSelectedToast(); // Show error notification if no emoji is selected
      return;
    }

    try {
      await writeCategory(`users/${user.uid}/categories`, {
        //categoryID is auto generated by firebase within the function
        categoryName: categoryToAdd,
        categoryColor: color.hex,
        categoryEmoji: selectedEmoji,
      });

      categoryAddedToast(); //success notifcaton

      isCategoryModalOpen && dispatch(toggleCategoryModal(false)); //close the category modal once a pin is added successfully
    } catch (error) {
      standardErrorToast(String(error));
    }
  };

  // Style for the active button
  const activeButtonStyle = {
    backgroundColor: isFlashing ? "#0056b3" : "#003d80", // Darker shades of blue
    transition: "background-color 0.4s ease",
  };

  return (
    <main className={isCategoryModalOpen ? styles.main : styles.fullScreen}>
      <h1>Add Category</h1>
      <form className={styles.form} onSubmit={(e) => addCategory(e)}>
        <div
          className={styles.inputContainer}
          style={{ "--category-color": color.hex } as React.CSSProperties}
        >
          <input
            required
            type="text"
            placeholder="Enter category name"
            value={categoryToAdd}
            onChange={(e) => setcategoryToAdd(e.target.value)}
          />
          <Emoji unified={selectedEmoji} />
        </div>

        <div className={styles.buttonContainer}>
          <button
            type="button"
            onClick={() => setEmojiPicker(false)}
            style={!emojiPicker ? activeButtonStyle : {}}
          >
            Color Picker
          </button>
          <button
            type="button"
            onClick={() => setEmojiPicker(true)}
            style={emojiPicker ? activeButtonStyle : {}}
          >
            Emoji Picker
          </button>
        </div>
        {emojiPicker ? (
          <div className={isCategoryModalOpen ? styles.emojiPicker : ""}>
            <EmojiPicker
              onEmojiClick={(emojiData) => {
                setselectedEmoji(emojiData.unified);
                console.log(emojiData.unified);
              }}
              categories={[]}
              skinTonesDisabled={true}
              previewConfig={{ showPreview: false }}
              className={styles.emojiPicker}
              height="20em"
            />
          </div>
        ) : (
          <div className={isCategoryModalOpen ? styles.modalContent : ""}>
            <ColorPicker
              color={color}
              onChange={setColor}
              hideInput={["hsv"]}
              hideAlpha={true}
            />
          </div>
        )}

        <button type="submit">Add Category</button>
      </form>
      {isCategoryModalOpen && (
        <button
          onClick={() => dispatch(toggleCategoryModal(false))}
          className={isCategoryModalOpen ? styles.exit : ""}
        >
          X
        </button>
      )}
    </main>
  );
}
